platform :ios, '8.0'

source 'https://github.ehealthinnovation.org/PHIT/CocoaPods.git'
use_frameworks!

target 'CCGlucose_Example' do
  pod 'CCGlucose', :path => '../'
  pod 'CCBluetooth', :git => 'https://github.com/uhnmdi/CCBluetooth.git'
  pod 'CCToolbox', :git => 'https://github.com/uhnmdi/CCToolbox.git'

  target 'CCGlucose_Tests' do
    inherit! :search_paths
    pod 'CCGlucose', :path => '../'
  end
end
