platform :ios, '8.0'

source 'https://github.ehealthinnovation.org/PHIT/CocoaPods.git'
use_frameworks!

target 'CCGlucose_Example' do
  pod 'CCGlucose', :path => '../'
  pod 'CCBluetooth'
  pod 'CCToolbox'

  target 'CCGlucose_Tests' do
    inherit! :search_paths
  end
end
